---
- name: Create security group
  amazon.aws.ec2_group:
    name: "{{ security_group_name }}"
    description: "{{ security_group_name }}"
    rules: "{{ security_group_rules }}"
    rules_egress: "{{ security_group_rules_egress }}"
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  register: security_group

- name: Test for presence of local keypair
  ansible.builtin.stat:
    path: "{{ keypair_path }}"
  register: keypair_local

- name: Delete remote keypair
  amazon.aws.ec2_key:
    name: "{{ keypair_name }}"
    state: absent
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  when: not keypair_local.stat.exists

- name: Create keypair
  amazon.aws.ec2_key:
    name: "{{ keypair_name }}"
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  register: keypair

- name: Persist the keypair
  ansible.builtin.copy:
    dest: "{{ keypair_path }}"
    content: "{{ keypair.results[0].key.private_key }}"
    mode: 0600
  when: keypair.results[0].msg == "key pair created"

- name: Get the ec2 ami(s) by owner and name, if image not set
  amazon.aws.ec2_ami_info:
    owners: "{{ image_owner }}"
    filters:
      name: "{{ image_name }}"
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  when: item.image is not defined
  register: ami_info

- name: Set AMI id
  ansible.builtin.set_fact:
    image: "{{ ami_info.results[-1].images[-1].image_id }}"
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  when: item.image is not defined

- name: Create molecule instance(s)
  amazon.aws.ec2:
    key_name: "{{ keypair_name }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    group: "{{ security_group_name }}"
    instance_tags:
      created_by: "{{ tag_created_by }}"
      instance: "{{ tag_name }}"
      Name: "{{ tag_name }}"
    wait: true
    assign_public_ip: true
    exact_count: 1
    count_tag:
      instance: "{{ item.name }}"
    volumes:
      - device_name: /dev/sda1
        delete_on_termination: yes
        volume_size: "{{ volume_size }}"
  register: server
  loop: "{{ molecule_yml.platforms }}"
  loop_control:
    index_var: index
  async: 7200
  poll: 0

- name: Wait for instance(s) creation to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: ec2_jobs
  until: ec2_jobs.finished
  retries: 300
  with_items: "{{ server.results }}"

# Mandatory configuration for Molecule to function.

- name: Populate instance config dict
  ansible.builtin.set_fact:
    instance_conf_dict: {
      'instance': "{{ item.instances[0].tags.instance }}",
      'address': "{{ item.instances[0].public_ip }}",
      'user': "{{ ssh_user }}",
      'port': "{{ ssh_port }}",
      'identity_file': "{{ keypair_path }}",
      'instance_ids': "{{ item.instance_ids }}",
      'group_id': "{{ security_group.results[0].group_id }}", }
  with_items: "{{ ec2_jobs.results }}"
  register: instance_config_dict
  when: server.changed | bool

- name: Convert instance config dict to a list
  ansible.builtin.set_fact:
    instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
  when: server.changed | bool

- name: Dump instance config
  copy:
    content: "{{ instance_conf | to_json | from_json | community.molecule.to_yaml }}"
    dest: "{{ molecule_instance_config }}"
  when: server.changed | bool

- name: Wait for SSH
  wait_for:
    port: "{{ ssh_port }}"
    host: "{{ item.address }}"
    search_regex: SSH
    delay: 10
    timeout: 320
  with_items: "{{ lookup('file', molecule_instance_config) | community.molecule.from_yaml }}"

- name: Wait for boot process to finish
  pause:
    minutes: 2
