---
version: 2.1

executors:
  ansible-lint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/ansible-lint:latest
    resource_class: small
  molecule:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors_molecule/molecule:ec2
    resource_class: small
  yamllint:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/yamllint:latest
    resource_class: small
  trailing-whitespace:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors/trailing-whitespace:latest
    resource_class: small

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  ansible-lint:
    executor: ansible-lint
    steps:
      - checkout
      - run:
          name: Install the role
          command: |
            ansible-galaxy install git+${CIRCLE_REPOSITORY_URL},${CIRCLE_SHA1}
      - run:
          name: Install dependent roles
          command: |
            for d in `find molecule/* -maxdepth 1`; do
              if [[ $d =~ molecule/.*/requirements.yml ]]; then
                ansible-galaxy install -r $d
              fi
            done
      - run:
          name: Install required Ansible Collections
          command: |
            ansible-galaxy collection install community.molecule
      - run:
          name: Execulte Ansible-lint
          command: ansible-lint
      - run:
          name: Show Ansible-lint version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible-lint --version
  molecule-env:
    executor: molecule
    parameters:
      scenario-name:
        type: string
    working_directory: ~/molecule_test_ec2
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Install jq
          command: |
            sudo apt -y update
            sudo apt -y install jq
      - run:
          name: Create AWS access key pair
          command: |
            aws_sts_credentials=$(aws sts assume-role-with-web-identity \
            --role-arn ${AWS_ROLE_ARN} \
            --web-identity-token ${CIRCLE_OIDC_TOKEN} \
            --role-session-name "circleci_molecule-ec2-test_env_<< parameters.scenario-name >>" \
            --duration-seconds 1800 \
            --query "Credentials" \
            --output "json")

            echo export AWS_ACCESS_KEY_ID="$(echo $aws_sts_credentials | jq -r '.AccessKeyId')" >> $BASH_ENV
            echo export AWS_SECRET_ACCESS_KEY="$(echo $aws_sts_credentials | jq -r '.SecretAccessKey')" >> $BASH_ENV
            echo export AWS_SESSION_TOKEN="$(echo $aws_sts_credentials | jq -r '.SessionToken')" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H%M%S")
            VALUE="molecule_molecule_test_ec2_env_<< parameters.scenario-name >>"
            AWSIAM_USER="${VALUE}_${TIMESTAMP}"
            AWSIAM_POLICY_NAME="${VALUE}_${TIMESTAMP}"
            echo "export AWSIAM_USER=$AWSIAM_USER" >> $BASH_ENV
            echo "export AWSIAM_POLICY_NAME=$AWSIAM_POLICY_NAME" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H:%M:%S")
            VALUE="molecule_molecule_test_ec2_env_<< parameters.scenario-name >>"
            AUTHOR_EMAIL=$(git show -s --format='%ae' ${CIRCLE_SHA1})

            echo "export CREATED_BY=${AUTHOR_EMAIL}" >> $BASH_ENV
            echo "export KEYPAIR_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export PLATFORM_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export SECURITY_GROUP_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export TAG_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install required Ansible Collections and roles
          command: |
            ansible-galaxy collection install community.molecule
      - run:
          name: Test with molecule
          command: |
            molecule test --scenario-name << parameters.scenario-name >>
          environment:
            ANSIBLE_FORCE_COLOR: 1
            # AMI_OWNER_ID: sotred in system environment variables
            # AWS_ACCESS_KEY_ID: sotred in system environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: stored in system environment variables
            # CREATED_BY: stored in CircleCI environment variables
            # KEYPAIR_NAME: sotred in CircleCI environment variables
            MOLECULE_VERBOSITY: 0
            # PLATFORM_NAME: sotred in CircleCI environment variables
            PROFILE_TASKS_SORT_ORDER: 'none'
            PROFILE_TASKS_TASK_OUTPUT_LIMIT: 200
            PY_COLORS: 1
            # SECURITY_GROUP_NAME: sotred in CircleCI environment variables
            # VPC_SUBNET_ID: sotred in CircleCI environment variables
            TZ: 'Asia/Tokyo'
      - run:
          name: Show Ansible version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible --version
      - run:
          name: Show Molecule version
          command: molecule --version
  molecule-profile:
    executor: molecule
    parameters:
      scenario-name:
        type: string
    working_directory: ~/molecule_test_ec2
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: molecule
          role-arn: ${AWS_ROLE_ARN}
          role-session-name: "circleci_molecule-ec2-test_profile_<< parameters.scenario-name >>"
          session-duration: '1800'
      - run:
          name: Set environment variable with timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H%M%S")
            VALUE="molecule_molecule_test_ec2_profile<< parameters.scenario-name >>"
            AWSIAM_USER="${VALUE}_${TIMESTAMP}"
            AWSIAM_POLICY_NAME="${VALUE}_${TIMESTAMP}"
            echo "export AWSIAM_USER=$AWSIAM_USER" >> $BASH_ENV
            echo "export AWSIAM_POLICY_NAME=$AWSIAM_POLICY_NAME" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Set timestamp for making sure Molecule would create unique AWS resources
          command: |
            TIMESTAMP=$(date --date "9 hours" "+%Y%m%d_%H:%M:%S")
            VALUE="molecule_molecule_test_ec2_profile_<< parameters.scenario-name >>"
            AUTHOR_EMAIL=$(git show -s --format='%ae' ${CIRCLE_SHA1})

            echo "export CREATED_BY=${AUTHOR_EMAIL}" >> $BASH_ENV
            echo "export KEYPAIR_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export PLATFORM_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export SECURITY_GROUP_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            echo "export TAG_NAME=${VALUE}_${TIMESTAMP}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install required Ansible Collections and roles
          command: |
            ansible-galaxy collection install community.molecule
      - run:
          name: Test with molecule
          command: |
            molecule test --scenario-name << parameters.scenario-name >>
          environment:
            ANSIBLE_FORCE_COLOR: 1
            # AMI_OWNER_ID: sotred in system environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            AWS_PROFILE: molecule
            # CREATED_BY: stored in CircleCI environment variables
            # KEYPAIR_NAME: sotred in CircleCI environment variables
            # PLATFORM_NAME: sotred in CircleCI environment variables
            PROFILE_TASKS_SORT_ORDER: 'none'
            PROFILE_TASKS_TASK_OUTPUT_LIMIT: 200
            PY_COLORS: 1
            # SECURITY_GROUP_NAME: sotred in CircleCI environment variables
            # VPC_SUBNET_ID: sotred in CircleCI environment variables
            TZ: 'Asia/Tokyo'
      - run:
          name: Show Ansible version
          command: |
            pip list | grep ansible \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
            ansible --version
      - run:
          name: Show Molecule version
          command: molecule --version
  yamllint:
    executor: yamllint
    steps:
      - checkout
      - run:
          name: Execute yamllint
          command: yamllint *
      - run:
          name: Show yamllint version
          command: |
            yamllint --version \
            | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
            | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
            | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
  trailing-whitespace:
    executor: trailing-whitespace
    steps:
      - checkout
      - run:
          name: Execute trailing-whitespace
          command: trailing-whitespace

workflows:
  version: 2.1
  build:
    jobs:
      - trailing-whitespace
      - yamllint:
          requires:
            - trailing-whitespace
      - ansible-lint:
          requires:
            - yamllint
      - molecule-env:
          context: aws-oidc
          matrix:
            parameters:
              scenario-name:
                - "ami_name_test"
                - "ami_id_test"
          requires:
            - ansible-lint
      - molecule-profile:
          context: aws-oidc
          matrix:
            parameters:
              scenario-name:
                - "ami_name_test"
                - "ami_id_test"
          requires:
            - ansible-lint
