---
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get profiles
      ansible.builtin.command: aws configure list-profiles
      register: profiles
      changed_when: false

    - name: Show profiles
      ansible.builtin.debug:
        var: profiles
