---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Execute
      ansible.builtin.include_role:
        name: molecule_test_ec2
      vars:
        resource_state: 'absent'
