---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance
    image: ${AMI_ID}
    instance_type: t2.micro
    keypair_name: ${KEYPAIR_NAME}
    security_group_name: ${SECURITY_GROUP_NAME}
    tag_name: ${TAG_NAME}
    tag_created_by: ${CREATED_BY}
    vpc_subnet_id: ${VPC_SUBNET_ID}
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    image: ${AMI_ID}
    instance_type: t2.micro
    keypair_name: ${KEYPAIR_NAME}
    security_group_name: ${SECURITY_GROUP_NAME}
    tag_name: ${TAG_NAME}
    tag_created_by: ${CREATED_BY}
    vpc_subnet_id: ${VPC_SUBNET_ID}
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - syntax
    - create
    - converge
    - destroy
